### ISSUE TITLE
process not closed in pipe

### ISSUE THREAD

**Issue by thijsdejong** [OscarMulder/codam-42sh#374]
```
$> base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e
s/0/No/g
{{ Displays "Yes" or "No" randomly }}
$> ps a | grep 'base64' | grep -v 'grep'
$>
```

We display:
```
vsh codam-42sh > base64 < /dev/urandom | head -c 1000 | grep 42 | wc -l | sed -e s/1/Yes/g -e s/0/No/g
       No
vsh codam-42sh > ps a | grep 'base64' | grep -v 'grep'
34686 s002  Z      0:00.00 (base64)
```

**Comment by jbrinksma** [comment]
Not sure if this is an actual bug, doesn't happen with me. Can you try this @robkuijper @marijnvanh ?

**Comment by robkuijper** [comment]
Ja, apart. Ik krijg idd ook niks bij die ps. Wel krijg ik bij nieuwe signal printing in pull #390 een SIGPIPE op het base64 proces (deze zou in principe gesloten moeten worden door een SIGTTIN/SIGGTOU ipv een SIGPIPE, weet niet of dat heel erg veel uit maakt...)

**Comment by jbrinksma** [comment]
Pretty sure it's supposed to get a SIGPIPE, since we are closing the read side of the pipe of the next process in the sequence

**Comment by marijnvanh** [comment]
I had the same issue on master but it seems to be fixed in logical_operation_fixes
