### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by thijsdejong** [OscarMulder/codam-42sh#380]
```
$> (cat < heredoc> abd
heredoc> abc
heredoc> abb
heredoc> EOF
abb$
abc$
abd$
$>
```

I have absolutely no clue what this test is and how it is supposed to do anything

**Comment by OscarMulder** [comment]
Bash doesn't do this so eeh yeah just ignore it?

**Comment by jbrinksma** [comment]
What is this supposed to be?

**Comment by thijsdejong** [comment]
@jbrinksma @OscarMulder The most logical thing I can think of is it's this:

```
vsh codam-42sh > cat -e << EOF
> abd
> abc
> abb
> EOF
abd$
abc$
abb$
vsh codam-42sh > 
```
This is ouput from our shell which makes sense and works perfectly fine, so I assume there is no issue with this. Closing :jack_o_lantern:
